name: Run Postman Intent Structure Automation Test

on:
  push:
    branches:
      - main

jobs:
  postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Install Newman HTML Extra Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run Postman Content Structure Automation Test
        id: postman-content-structure-automation-test
        run: |
          # Pass GitHub environment variables to Postman using --env-var
          newman run ${{ github.workspace }}/postman/IntentStructureAutomationTestPostmanCollection.json \
            --env-var "knowledgeHubUrl=${{ vars.KNOWLEDGE_HUB_URL }}" \
            --env-var "intentApiKey=${{ secrets.INTENT_API_KEY }}" \
            --iteration-data ${{ github.workspace }}/test/data/QA_Test_Cases.csv \
            -r htmlextra \
            --reporter-htmlextra-export ${{ github.workspace }}/QA_Test_Cases_Report.html
          exit_code=$?
          # Use GITHUB_ENV for cross-step variable
          echo "exit_code=$exit_code" >> $GITHUB_ENV
        continue-on-error: true # This lets us still continue after test failure

      - name: Sanitize HTML report (replace GitHub secrets with ****)
        run: |
          sed -i "s/${INTENT_API_KEY}/********/g" "$GITHUB_WORKSPACE/QA_Test_Cases_Report.html"
        env:
          INTENT_API_KEY: ${{ secrets.INTENT_API_KEY }}

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: QA_Test_Cases_Report
          path: ${{ github.workspace }}/QA_Test_Cases_Report.html

      - name: Validate Postman Content Structure Automation Test Outcome
        if: env.exit_code != '0'
        run: |
          echo "Postman tests failed with exit code ${{ env.exit_code }}"
          exit 1  # Force failure if the exit code is not 0